### ISSUE TITLE
Problem when Merged Ticket gets an Follow Up

### ISSUE THREAD

**Issue by hanneshal** [znuny/Znuny4OTRS-MarkTicketSeenUnseen#2]
After two tickets are merged, and you try to mark an article as unseen which was added after the merge you get an error message:

'Can't find Article XXXX of ticket with id XXX'

I think we need to implement a check for merged tickets. Doh!

**Comment by dennykorsukewitz** [comment]
@hanneshal 
I can not reproduce this error. Is this still intact?

**Comment by dennykorsukewitz** [comment]
Close issue - is not reproducible. Error is no longer present in the current framework version. ( 4 & 5)
