### ISSUE TITLE
Version 6.0.2 - Comment shown in LoginBox on Agent Login page

### ISSUE THREAD

**Issue by meisterheister** [znuny/Znuny4OTRS-MarkTicketSeenUnseen#5]
There is a comment shown if Znuny4OTRS-MarkTicketSeenUnseen v 6.0.2 is installed above the agent login (/otrs/index.pl) "Dialog, der angezeigt wird, nachdem ein Ticket als gelesen markiert wurde." (German) which should not be there.

![image](https://user-images.githubusercontent.com/35762852/35382382-5a2a8a0a-01bf-11e8-9b5b-57a6bb084aee.png)

**Comment by jepf** [comment]
@meisterheister 
Thank you for reporting this. It has been fixed in package version 6.0.3.
